version: "3"
services:
  testdb:
    image: postgres
    restart: always
    container_name: item_db_test
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=mysecretpassword"
      - "POSTGRES_DB=postgres"
    ports:
      - 44217:5432